name: S2I Fuse Java Build
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  s2i-build:
    runs-on: ubuntu-latest
    env:
      # Default values that can be overridden via repository secrets or variables
      PATH_CONTEXT: .
      TLSVERIFY: 'true'
      MAVEN_ARGS_APPEND: ${{ vars.MAVEN_ARGS_APPEND || '' }}
      MAVEN_CLEAR_REPO: ${{ vars.MAVEN_CLEAR_REPO || 'false' }}
      MAVEN_MIRROR_URL: ${{ vars.MAVEN_MIRROR_URL || '' }}
      # ECR related variables
      AWS_REGION: ${{ vars.AWS_REGION || 'us-west-2' }}
      # Base image repository name
      ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY_NAME }}
      # Target repository for the built image
      TARGET_REPOSITORY: fuse-test-services
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: true
        
      - name: Pull base image from ECR
        run: |
          # Get the ECR registry URL
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          
          # Extract just the repository name
          REPO_NAME="${{ env.ECR_REPOSITORY }}"
          
          # Construct the proper ECR image URI
          ECR_IMAGE_URI=${ECR_REGISTRY}/${REPO_NAME}:latest
          
          echo "ECR Registry: ${ECR_REGISTRY}"
          echo "Repository Name: ${REPO_NAME}"
          echo "Pulling image from ${ECR_IMAGE_URI}"
          
          # Pull the image
          docker pull ${ECR_IMAGE_URI}
          
          # Store the full image URI for later use
          echo "BASE_IMAGE_URI=${ECR_IMAGE_URI}" >> $GITHUB_ENV
          
          # Verify the image was pulled
          docker images

      - name: Install S2I
        run: |
          curl -s https://api.github.com/repos/openshift/source-to-image/releases/tags/v1.4.0 | \
          grep browser_download_url | \
          grep linux-amd64 | \
          cut -d '"' -f 4 | \
          wget -qi -
          tar -xvf source-to-image*.tar.gz
          sudo mv s2i /usr/local/bin/
          rm -f source-to-image*.tar.gz
          
      - name: Generate environment file
        run: |
          echo "MAVEN_CLEAR_REPO=$MAVEN_CLEAR_REPO" > env-file
          if [[ '${{ env.MAVEN_ARGS_APPEND }}' != "" ]]; then
            echo "MAVEN_ARGS_APPEND=${{ env.MAVEN_ARGS_APPEND }}" >> env-file
          fi
          if [[ '${{ env.MAVEN_MIRROR_URL }}' != "" ]]; then
            echo "MAVEN_MIRROR_URL=${{ env.MAVEN_MIRROR_URL }}" >> env-file
          fi
          echo "Generated Env file"
          echo "------------------------------"
          cat env-file
          echo "------------------------------"
          
      - name: S2I Generate Dockerfile
        run: |
          s2i build ${{ env.PATH_CONTEXT }} ${BASE_IMAGE_URI} \
            --image-scripts-url image:///usr/local/s2i \
            --as-dockerfile ./Dockerfile.gen \
            --environment-file ./env-file
            
      # We don't need a separate login step since we already logged into ECR earlier
          
      - name: Build and push to ECR
        if: github.event_name != 'pull_request'
        run: |
          # Get the ECR registry URL
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          
          # Define target image name
          TARGET_IMAGE="${ECR_REGISTRY}/${{ env.TARGET_REPOSITORY }}:${{ github.sha }}"
          LATEST_TAG="${ECR_REGISTRY}/${{ env.TARGET_REPOSITORY }}:latest"
          
          echo "Building and pushing to ${TARGET_IMAGE}"
          
          # Build using the generated Dockerfile
          docker build -f ./Dockerfile.gen -t ${TARGET_IMAGE} -t ${LATEST_TAG} .
          
          # Push the image to ECR
          docker push ${TARGET_IMAGE}
          docker push ${LATEST_TAG}
          
          # Save the image URI for later steps
          echo "TARGET_IMAGE=${TARGET_IMAGE}" >> $GITHUB_ENV
          
      - name: Extract image digest
        if: github.event_name != 'pull_request'
        id: image-digest
        run: |
          DIGEST=$(docker inspect ${TARGET_IMAGE} --format='{{index .RepoDigests 0}}' | cut -d'@' -f2)
          echo "IMAGE_DIGEST=$DIGEST" >> $GITHUB_OUTPUT
          echo "IMAGE_DIGEST=$DIGEST" >> $GITHUB_ENV
          
      - name: Deploy to environment
        if: github.event_name != 'pull_request'
        run: |
          echo "Deploying image ${TARGET_IMAGE}@${{ env.IMAGE_DIGEST }} to environment..."
          # Add your deployment commands here
          # For example with kubectl:
          # kubectl set image deployment/your-app your-container=${{ env.IMAGE }}@${{ env.IMAGE_DIGEST }}